name: "Test and lint"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - name: "Install dependencies"
        uses: jdx/mise-action@v2
        with:
          cache: true
      - name: "Run test suite"
        env:
          SECRET_KEY: "${{ secrets.SECRET_KEY_FOR_TESTS }}"
        run: |
          make test
      - name: "Save the result of test suite"
        run: |
          echo "Nothing to save"
  test-lint:
    name: "Linting"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - name: "Install dependencies"
        uses: jdx/mise-action@v2
        with:
          cache: true
      - name: "Run linting"
        run: |
          make lint
  test-coverage:
    name: "Test coverage"
    needs: [test]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      badge_url: ${{ steps.upload-coverage-badge-artifact-step.outputs.artifact-url }}
      html_report_url: ${{ steps.upload-html-report-artifact-step.outputs.artifact-url }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - name: "Install dependencies"
        uses: jdx/mise-action@v2
        with:
          cache: true
      - name: "Run test coverage check"
        env:
            SECRET_KEY: "${{ secrets.SECRET_KEY_FOR_TESTS }}"
            # This is explicitly a prototype, so no need to worry about test
            # coverage. We'll keep the step for info, as it doesn't take long,
            # just set the minimum coverage figure to zero:
            FAIL_IF_UNDER: 0
        run: |
          make test-coverage
      - name: "Save the coverage check result"
        uses: actions/upload-artifact@v4
        id: upload-html-report-artifact-step
        if: always()
        with:
          name: coverage-html
          path: htmlcov
          retention-days: 10
          compression-level: 0
      - name: "Save the coverage check badge"
        uses: actions/upload-artifact@v4
        id: upload-coverage-badge-artifact-step
        if: always()
        with:
          name: coverage-badge
          path: coverage.svg
          retention-days: 10
          compression-level: 0